<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class RenewUserHistory extends Model
{
	protected $table = 'slj_renew_user_history';
	protected $fillable = [
		'order_number',
		'distributor',
		'branch',
		'franchise',
		'franchise_name',  
		'customer_id',
		'renew_cycle',
		'renew_type',
		'confirmed',
		'scheduled_datetime',
		'connection_type',
		'package',
		'sub_package',
		'combo_package',
		'combo_sub_package',
		'cable_allacart',
		'cable_packages',
		'cable_base',
		'cable_local',
		'iptv_allacart',
		'iptv_packages',
		'iptv_base',
		'iptv_local',
		'enable_discount',
		'discount_reason',
		'discount_amount',
		'enable_additional_charges',  
		'additional_charges_reason',
		'additional_amount',
		'department',
		'assigned_to',
		'payment_status',
		'paid_amount',
		'payment_type',
		'bill_address',
		'invoice_comment',
		'new_expiry_date',
		'package_amount',
		'invoice_amount',
		'final_payable',
		'payment',
		'ref_no',
		'customer_renewed',
		'generate_invoice',
		'cheque_no',
		'bank_name',
		'cheque_date',
		'bill_comment',
		'csbu',
		'ccsbu',
		'clconnectiontype',
		'cle',
		'clp',
		'clsp',
		'clcp',
		'clcsp',
		'clcpa',
		'clca',
		'clcb',
		'clcl',
		'clip',
		'clia',
		'clib',
		'clil',
		'confirmed',
		'renew_by',
		'user_id',
		'from_date',
		'end_date',
		'paid_date',
		'installation_address',
		'time'
	];

}
